<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Promise객체</title>
</head>
<body>
	<!-- myinfo/promise.html -->
	<script>
	//pending,fullfilled,rejected
	let promise = new Promise(function(resolve, reject){ //promise객체 함수의 또 그 안의 매개값 /첫번째 resolve가 실행되면 밑에 success
		resolve('Success');	
		//reject('Fail'); //이행이 거부됐을때 reject가 실행됨
	});
	
	promise
		.then(function(result){ //(이행완료)정상적으로 이행이 완료되면 then 이 실행됨/위의 Success가 result로 전달이 됨
			console.log('result: ', result)
			return 'Second!';
		}) 
		.then(function(data){ //비동기적인 방식인것을 순차적으로 기능하기 위해 마치 동기방식처럼/위에서 반환한값을 받아서 ~ 순차적으로 내려가(promise)
			console.log('date: ', data);
			return 'Third';
		})
		.then(function(output){
			console.log('output: ', output); //여기서 오류발생하게해야하는 왜 안나지
			//return 
		})
		.catch(function(err){ //이행이 거부가 됨
			console.log('err: ', err);
		}) 
	</script>
</body>
</html>